# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAndReg', '0002_auto_20170123_2009'),
        ('wish_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishes',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='LoginAndReg.User'),
            preserve_default=False,
        ),
    ]
