# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAndReg', '0002_auto_20170123_2009'),
        ('wish_list', '0002_wishes_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishes',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='wishes',
            name='added_by',
            field=models.ManyToManyField(related_name='user_item', to='LoginAndReg.User'),
        ),
    ]
