# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0003_auto_20170206_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishes',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_item', to='LoginAndReg.User'),
        ),
    ]
